# Generated by Django 5.1.10 on 2025-07-05 17:07

import django.db.models.deletion
import django_jsonform.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0010_userdevice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageContext",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
            ],
            options={
                "verbose_name": "Message Context",
            },
        ),
        migrations.CreateModel(
            name="NotificationAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.SlugField(max_length=255, unique=True)),
                ("provider", models.CharField(max_length=255)),
                ("type", models.CharField(blank=True, choices=[("sms", "sms"), ("fcm", "fcm")], max_length=15)),
                ("extras", models.JSONField(blank=True, null=True)),
                ("cost_ratio", models.DecimalField(decimal_places=2, default=1, max_digits=6)),
            ],
            options={
                "verbose_name": "Notification Account",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("final_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "to_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="notifications.notificationaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ForeignTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("const_message_key", models.CharField(max_length=255)),
                ("foreign_template_name", models.CharField(max_length=255)),
                ("foreign_mapping", django_jsonform.models.fields.JSONField()),
                (
                    "notification_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="foreigntemplate",
                        to="notifications.notificationaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foreign Template",
            },
        ),
        migrations.CreateModel(
            name="NotifiedMessageContext",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "as_var",
                    models.CharField(
                        choices=[
                            ("body", "Body"),
                            ("title", "Title"),
                            ("link", "Link"),
                            ("icon_url", "Icon Url"),
                            ("image_url", "Image Url"),
                        ],
                        max_length=63,
                    ),
                ),
                ("actual_message", models.TextField()),
                (
                    "foreign_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifiedmessagecontext",
                        to="notifications.foreigntemplate",
                    ),
                ),
                (
                    "message_context",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifiedmessagecontext",
                        to="notifications.messagecontext",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifiedmessagecontext",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notified Message Context",
            },
        ),
        migrations.CreateModel(
            name="FCM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.TextField()),
                (
                    "user_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fcm_set", to="core.userdevice"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_set",
                        to="notifications.notificationaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "FCM",
                "constraints": [
                    models.UniqueConstraint(fields=("user_device", "account"), name="unique_for_device_and_account")
                ],
            },
        ),
    ]
