# Generated by Django 5.2.8 on 2025-11-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teleport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="toturial_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
