# Generated by Django 5.2.8 on 2025-12-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teleport", "0002_panel_toturial_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="member_subscription_notif",
            field=models.BooleanField(default=True),
        ),
    ]
