# Generated by Django 5.2.8 on 2025-12-26 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
        ("teleport", "0003_panel_member_subscription_notif"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="toturial_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="telegram_bot.telegrammessage",
            ),
        ),
    ]
