# Generated by Django 5.2.8 on 2025-12-09 12:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentprovider",
            name="currencies",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("EUR", "Euro"), ("IRR", "Iranian Rial"), ("USD", "US Dollar")], max_length=4
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
