# Generated by Django 5.2.8 on 2025-11-13 14:11

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("IRR", "Iranian Rial"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="total_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("IRR", "Iranian Rial"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("IRR", "Iranian Rial"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("IRR", "Iranian Rial"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
    ]
