# Generated by Django 5.2.8 on 2025-11-17 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_invoiceitem_created_by_paymentprovider_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
