# Generated by Django 5.2.8 on 2025-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_invoice_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_date",
        ),
        migrations.AddField(
            model_name="payment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Initiated"), (2, "Pending"), (3, "Completed"), (4, "Failed"), (5, "Refunded")], default=2
            ),
        ),
    ]
