# Generated by Django 4.2.17 on 2025-02-11 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionNodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_oid', models.PositiveIntegerField()),
                ('node_oid', models.PositiveIntegerField()),
                ('upload_traffic', models.PositiveSmallIntegerField()),
                ('download_traffic', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xray_uuid', models.UUIDField(blank=True)),
                ('expiry', models.DurationField(blank=True, null=True)),
                ('upload_limit_bytes', models.PositiveBigIntegerField()),
                ('download_limit_bytes', models.PositiveBigIntegerField()),
                ('total_limit_bytes', models.PositiveBigIntegerField()),
                ('description', models.TextField(max_length=4095)),
                ('is_active', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
