# Generated by Django 4.2.17 on 2025-02-22 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sublink_title_template', models.TextField(blank=True, help_text='{{ subscription_obj }}', null=True)),
                ('sublink_header_template', models.TextField(blank=True, help_text='{{ subscription_obj }}', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField()),
                ('inbound_template', models.TextField(help_text='{{ subscription_obj }}')),
                ('link_template', models.TextField(help_text='{{ subscriptionperiod_obj }}')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionNodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_oid', models.PositiveIntegerField()),
                ('node_oid', models.PositiveIntegerField()),
                ('upload_traffic', models.PositiveSmallIntegerField()),
                ('download_traffic', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=127)),
                ('uuid', models.UUIDField(unique=True)),
                ('xray_uuid', models.UUIDField(blank=True, unique=True)),
                ('expiry', models.DurationField(blank=True, null=True)),
                ('upload_limit_bytes', models.PositiveBigIntegerField()),
                ('download_limit_bytes', models.PositiveBigIntegerField()),
                ('total_limit_bytes', models.PositiveBigIntegerField()),
                ('description', models.TextField(blank=True, max_length=4095, null=True)),
                ('is_active', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
