# Generated by Django 5.1.7 on 2025-04-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0001_big_migration_1"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Inbound",
            new_name="InboundType",
        ),
        migrations.AddField(
            model_name="inboundtype",
            name="haproxy_backend",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inboundtype",
            name="haproxy_matcher",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inboundtype",
            name="link_template",
            field=models.TextField(blank=True, help_text="{{ subscriptionperiod_obj }}", null=True),
        ),
        migrations.AlterField(
            model_name="inboundtype",
            name="nginx_path_config",
            field=models.TextField(blank=True, null=True),
        ),
    ]
