# Generated by Django 5.1.7 on 2025-05-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0002_rename_inbound_inboundtemplate_inboundgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionperiod",
            name="flow_download_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionperiod",
            name="flow_point_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionperiod",
            name="flow_upload_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionperiod",
            name="last_flow_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
