# Generated by Django 4.2.17 on 2025-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0002_subscription_current_download_bytes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='sublink_title_template',
        ),
        migrations.AlterField(
            model_name='config',
            name='sublink_header_template',
            field=models.TextField(help_text='{{ subscription_obj }}', null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='inbound_template',
            field=models.TextField(help_text='{{ node_obj }}'),
        ),
    ]
