# Generated by Django 4.2.17 on 2025-02-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0003_remove_config_sublink_title_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='nginx_config_template',
            field=models.TextField(help_text='{{ subscription_obj }}', null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='link_template',
            field=models.TextField(blank=True, help_text='{{ subscription_obj }}'),
        ),
    ]
