# Generated by Django 5.1.7 on 2025-05-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0003_subscriptionperiod_flow_download_bytes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inboundtype",
            old_name="haproxy_matcher",
            new_name="haproxy_matcher_80",
        ),
        migrations.AddField(
            model_name="inboundtype",
            name="haproxy_matcher_443",
            field=models.TextField(blank=True, null=True),
        ),
    ]
