# Generated by Django 5.1.7 on 2025-05-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0004_rename_haproxy_matcher_inboundtype_haproxy_matcher_80_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agency",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="agent",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="config",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="connectionrule",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="inboundtype",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="isp",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="nodeoutbound",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="outboundgroup",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="subscriptionnodeusage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="subscriptionperiod",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="subscriptionprofile",
            options={"ordering": ["-created_at"]},
        ),
    ]
