# Generated by Django 4.2.17 on 2025-02-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0005_inbound_nginx_path_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='nginx_config_template',
            new_name='nginx_config_http_template',
        ),
    ]
