# Generated by Django 4.2.17 on 2025-02-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0006_rename_nginx_config_template_config_nginx_config_http_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='nginx_config_stream_template',
            field=models.TextField(help_text='{{ node_obj }}', null=True),
        ),
    ]
