# Generated by Django 5.1.7 on 2025-05-13 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0021_ordering_created_at"),
        ("proxy_manager", "0006_inboundcombogroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodeoutbound",
            name="xray_outbound_template",
            field=models.TextField(help_text="{{ node, tag, nodeinternaluser }}"),
        ),
        migrations.CreateModel(
            name="InternalUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("xray_uuid", models.UUIDField(blank=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "connection_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="proxy_manager.connectionrule",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="node_manager.node"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("connection_rule", "node"), name="unique_connection_rule_ip")
                ],
            },
        ),
    ]
