# Generated by Django 4.2.17 on 2025-02-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0007_config_nginx_config_stream_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='xray_config_template',
            field=models.TextField(help_text='{{ subscription_obj }}', null=True),
        ),
    ]
