# Generated by Django 4.2.17 on 2025-02-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0008_config_xray_config_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
