# Generated by Django 5.1.7 on 2025-05-30 14:26

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_siteconfiguration_sync_brake"),
        ("net_manager", "0001_initial"),
        ("node_manager", "0023_alter_supervisorprocessinfo_pid"),
        ("proxy_manager", "0008_remove_nodeoutbound_group_alter_internaluser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionrule",
            name="inbound_choose_rule",
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="connectionrule",
            name="inboundcombogroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inboundcombogroup_connectionrules",
                to="proxy_manager.inboundcombogroup",
            ),
        ),
        migrations.CreateModel(
            name="InboundSpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.SlugField(unique=True)),
                ("port", models.PositiveSmallIntegerField()),
                (
                    "domain_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="net_manager.dnsrecord",
                    ),
                ),
                (
                    "domain_sni",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domainsni_inboundflatcombinations",
                        to="core.domain",
                    ),
                ),
                (
                    "domainhost_header",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domainhostheader_inboundflatcombinations",
                        to="core.domain",
                    ),
                ),
                (
                    "inbound_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inboundtype_combinations",
                        to="proxy_manager.inboundtype",
                    ),
                ),
                (
                    "ip_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="node_manager.publicip",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConnectionRuleInboundSpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=63)),
                ("weight", models.PositiveSmallIntegerField(default=0)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_connectionruleinboundspecs",
                        to="proxy_manager.connectionrule",
                    ),
                ),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="proxy_manager.inboundspec"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
