# Generated by Django 4.2.17 on 2025-03-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0009_inbound_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField()),
                ('xray_rules_template', models.TextField(help_text='[RuleObject]')),
                ('destination_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationregion_connectionrules', to='proxy_manager.region')),
                ('origin_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originregion_connectionrules', to='proxy_manager.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='connection_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='connectionrule_subscriptions', to='proxy_manager.connectionrule'),
        ),
    ]
