# Generated by Django 5.1.7 on 2025-05-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0009_connectionrule_inbound_choose_rule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodeoutbound",
            name="inbound_spec",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inboundspec_nodeoutbounds",
                to="proxy_manager.inboundspec",
            ),
        ),
        migrations.AlterField(
            model_name="nodeoutbound",
            name="xray_outbound_template",
            field=models.TextField(
                help_text="{{ node, tag, nodeinternaluser, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}"
            ),
        ),
    ]
