# Generated by Django 5.1.7 on 2025-06-01 10:30

import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0023_alter_supervisorprocessinfo_pid"),
        ("proxy_manager", "0010_nodeoutbound_inbound_spec_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="nodeoutbound",
            name="unique_name_node",
        ),
        migrations.AddField(
            model_name="nodeoutbound",
            name="balancer_allocation_str",
            field=models.CharField(help_text="balancertag1:weght,balancertag1:weght", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nodeoutbound",
            name="rule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rule_nodeoutbounds",
                to="proxy_manager.connectionrule",
            ),
        ),
    ]
