# Generated by Django 4.2.17 on 2025-03-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0010_isp_region_connectionrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='xray_config_template',
            field=models.TextField(help_text='{{ node, inbound_parts, rule_parts }}', null=True),
        ),
    ]
