# Generated by Django 4.2.17 on 2025-03-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0011_inbound_is_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrule',
            name='xray_rules_template',
            field=models.TextField(help_text='[RuleObject], {{ node, inbound_tags }}'),
        ),
    ]
