# Generated by Django 4.2.17 on 2025-03-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0013_outboundgroup_nodeoutbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='consumers_obj_template',
            field=models.TextField(default='hello', help_text='{{ subscription_obj }}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='xray_config_template',
            field=models.TextField(help_text='{{ node, inbound_parts, rule_parts, balancer_parts }}', null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='inbound_template',
            field=models.TextField(help_text='{{ node_obj, inbound_tag }}'),
        ),
        migrations.AlterField(
            model_name='outboundgroup',
            name='name',
            field=models.SlugField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='nodeoutbound',
            constraint=models.UniqueConstraint(fields=('name', 'node'), name='unique_name_node'),
        ),
    ]
