# Generated by Django 5.1.7 on 2025-06-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0024_publicip_asn_publicip_same_asn_domain"),
        ("proxy_manager", "0013_remove_connectionruleoutbound_part3"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundspec",
            name="touch_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="node_manager.node",
            ),
        ),
    ]
