# Generated by Django 4.2.17 on 2025-03-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0014_inbound_consumers_obj_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbound',
            old_name='consumers_obj_template',
            new_name='consumer_obj_template',
        ),
        migrations.AlterField(
            model_name='inbound',
            name='inbound_template',
            field=models.TextField(help_text='{{ node_obj, inbound_tag, consumers_part }}'),
        ),
    ]
