# Generated by Django 5.1.7 on 2025-06-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0014_inboundspec_touch_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodeoutbound",
            name="inbound_spec",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inboundspec_nodeoutbounds",
                to="proxy_manager.inboundspec",
            ),
        ),
    ]
