# Generated by Django 5.1.7 on 2025-06-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0024_publicip_asn_publicip_same_asn_domain"),
        ("proxy_manager", "0015_alter_nodeoutbound_inbound_spec"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reverse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.SlugField()),
                (
                    "balancer_allocation_str",
                    models.CharField(help_text="balancertag1:weght,balancertag1:weght", max_length=255),
                ),
                (
                    "xray_outbound_template",
                    models.TextField(
                        help_text="{{ node, tag, nodeinternaluser, combo_stat: {'address', 'port', 'sni', 'domainhostheader', 'touch_node'} }}"
                    ),
                ),
                ("base_conn_uuid", models.UUIDField()),
                (
                    "bridge_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fromnode_reverses",
                        to="node_manager.node",
                    ),
                ),
                (
                    "inbound_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inboundspec_reverses",
                        to="proxy_manager.inboundspec",
                    ),
                ),
                (
                    "portal_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tonode_reverses",
                        to="node_manager.node",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_reverses",
                        to="proxy_manager.connectionrule",
                    ),
                ),
                (
                    "to_inbound_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toinboundtype_reverses",
                        to="proxy_manager.inboundtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "bridge_node", "rule"), name="unique_name_bridgenode_rule_reverse"
                    ),
                    models.UniqueConstraint(
                        fields=("name", "portal_node", "rule"), name="unique_name_portalnode_rule_reverse"
                    ),
                ],
            },
        ),
    ]
