# Generated by Django 4.2.17 on 2025-03-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0016_agency_subscription_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='sublink_header_template',
        ),
        migrations.AddField(
            model_name='subscription',
            name='first_usage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_sublink_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_usage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
