# Generated by Django 5.1.10 on 2025-06-05 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0016_reverse"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="capacity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="AgencyPlanSpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("capacity", models.PositiveIntegerField()),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agency_agencyplanspecs",
                        to="proxy_manager.agency",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_agencyplanspecs",
                        to="proxy_manager.subscriptionplan",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("agency", "plan"), name="unique_agency_plan")],
            },
        ),
    ]
