# Generated by Django 4.2.17 on 2025-03-10 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proxy_manager', '0017_remove_config_sublink_header_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_as_current', models.BooleanField()),
                ('expiry', models.DurationField()),
                ('upload_limit_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('download_limit_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_limit_bytes', models.PositiveBigIntegerField()),
                ('last_sublink_at', models.DateTimeField(blank=True, null=True)),
                ('first_usage_at', models.DateTimeField(blank=True, null=True)),
                ('last_usage_at', models.DateTimeField(blank=True, null=True)),
                ('current_download_bytes', models.PositiveBigIntegerField(default=0)),
                ('current_upload_bytes', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField()),
                ('plan_provider_key', models.SlugField(max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=127)),
                ('uuid', models.UUIDField(unique=True)),
                ('xray_uuid', models.UUIDField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=4095, null=True)),
                ('is_active', models.BooleanField()),
                ('connection_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='connectionrule_subscriptionprofiles', to='proxy_manager.connectionrule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='agency',
            name='sublink_header_template',
            field=models.TextField(help_text='{{ subscription_obj, expires_at }}', null=True),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddField(
            model_name='subscriptionprofile',
            name='initial_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initialagency_subscriptionprofiles', to='proxy_manager.agency'),
        ),
        migrations.AddField(
            model_name='subscriptionprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionperiod',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='proxy_manager.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionperiod',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='proxy_manager.subscriptionprofile'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('selected_as_current', True)), fields=('profile',), name='one_selected_as_current_each_profile'),
        ),
    ]
