# Generated by Django 4.2.17 on 2025-03-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0018_subscriptionperiod_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionprofile',
            name='connection_rule',
        ),
        migrations.AddField(
            model_name='subscriptionperiod',
            name='plan_args',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='connection_rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='connectionrule_subscriptionplans', to='proxy_manager.connectionrule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_provider_args',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
