# Generated by Django 5.1.10 on 2025-07-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0019_historicalconfig_historicalconnectionrule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="haproxy_config_template",
            field=models.TextField(
                blank=True,
                help_text="{{ node_obj, xray_backends_part, xray_80_matchers_par, xray_443_matchers_part }}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalconfig",
            name="haproxy_config_template",
            field=models.TextField(
                blank=True,
                help_text="{{ node_obj, xray_backends_part, xray_80_matchers_par, xray_443_matchers_part }}",
                null=True,
            ),
        ),
    ]
