# Generated by Django 4.2.17 on 2025-03-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0019_remove_subscriptionprofile_connection_rule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionperiod',
            name='download_limit_bytes',
        ),
        migrations.RemoveField(
            model_name='subscriptionperiod',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='subscriptionperiod',
            name='total_limit_bytes',
        ),
        migrations.RemoveField(
            model_name='subscriptionperiod',
            name='upload_limit_bytes',
        ),
        migrations.AlterField(
            model_name='subscriptionperiod',
            name='plan_args',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_provider_args',
            field=models.JSONField(blank=True),
        ),
    ]
