# Generated by Django 5.1.10 on 2025-07-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0032_o2spec_keep_latest_config"),
        ("proxy_manager", "0020_config_haproxy_config_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundtype",
            name="compatible_cores",
            field=models.ManyToManyField(blank=True, to="node_manager.programversion"),
        ),
    ]
