# Generated by Django 5.1.10 on 2025-07-15 17:50

import django.db.models.deletion
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0020_config_haproxy_config_template_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPeriodAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accessed_at", models.DateTimeField()),
                ("source_ip", netfields.fields.InetAddressField(max_length=39)),
                ("inbound_tag_name", models.CharField(max_length=255)),
                ("outbound_tag_name", models.CharField(max_length=255)),
                ("dest_address", models.CharField(max_length=255)),
                ("dest_port", models.PositiveSmallIntegerField()),
                ("dest_protocol", models.CharField(max_length=63)),
                (
                    "subscription_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="proxy_manager.subscriptionperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
