# Generated by Django 5.1.10 on 2025-08-01 08:48

import django.db.models.deletion
from django.db import migrations, models


def populate(apps, schema_editor):
    PublicIP = apps.get_model('node_manager', 'PublicIP')
    RealitySpec = apps.get_model('proxy_manager', 'RealitySpec')
    for i in PublicIP.objects.filter(same_asn_domain__isnull=False):
        RealitySpec.objects.create(
            port=443,
            certificate_domain=i.same_asn_domain,
            for_ip=i,
        )

def reverse_populate(apps, schema_editor):
    RealitySpec = apps.get_model('proxy_manager', 'RealitySpec')
    for i in RealitySpec.objects.all():
        i.for_ip.same_asn_domain = i.certificate_domain
        i.for_ip.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_publickey"),
        ("node_manager", "0033_node_is_revoked"),
        ("proxy_manager", "0020_config_haproxy_config_template_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealitySpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("port", models.PositiveSmallIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "certificate_domain",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="core.domain"),
                ),
                (
                    "dest_ip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="node_manager.publicip",
                    ),
                ),
                (
                    "for_ip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="node_manager.publicip"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.RunPython(populate, reverse_code=reverse_populate),
    ]
