# Generated by Django 5.1.10 on 2025-07-18 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0020_config_haproxy_config_template_and_more"),
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="defualt_timezone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="telegrambot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="telegram_bot.telegrambot",
            ),
        ),
    ]
