# Generated by Django 4.2.17 on 2025-03-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0020_remove_subscriptionperiod_download_limit_bytes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionperiod',
            name='plan_args',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_provider_args',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
