# Generated by Django 5.1.10 on 2025-08-09 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0021_realityspec"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionRuleBalancer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.SlugField(max_length=63)),
                ("strategy_template", models.TextField(blank=True, null=True)),
                (
                    "connection_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balancers",
                        to="proxy_manager.connectionrule",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "connection_rule"),
                        name="balancer_unique_name_connection_rule",
                        violation_error_message="already exists with this name for this connection rule",
                    )
                ],
            },
        ),
    ]
