# Generated by Django 5.1.10 on 2025-07-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0022_agencyplanspec_is_active_agencyusergroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencyplanspec",
            name="price_provider_args",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agencyplanspec",
            name="price_provider_key",
            field=models.SlugField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="agencyusergroupplanspec",
            name="price_provider_args",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agencyusergroupplanspec",
            name="price_provider_key",
            field=models.SlugField(blank=True, max_length=127, null=True),
        ),
    ]
