# Generated by Django 5.1.7 on 2025-04-24 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0024_alter_customconfig_program_version_delete_xrayconfig"),
        ("proxy_manager", "0022_agency_is_active_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="geoip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="geoip_xrayconfig",
                to="node_manager.programversion",
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="geosite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="geosite_xrayconfig",
                to="node_manager.programversion",
            ),
        ),
    ]
