# Generated by Django 5.1.10 on 2025-08-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0023_balancer_config_tunnel_dest_ports_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboundcombodomainaddress",
            name="combo",
        ),
        migrations.RemoveField(
            model_name="inboundcombodomainhostheader",
            name="combo",
        ),
        migrations.RemoveField(
            model_name="inboundcombodomainsni",
            name="combo",
        ),
        migrations.RemoveField(
            model_name="inboundcomboipaddress",
            name="combo",
        ),
        migrations.RemoveField(
            model_name="inboundcombochoicegroup",
            name="combo",
        ),
        migrations.RemoveField(
            model_name="inboundcombochoicegroup",
            name="group",
        ),
        migrations.RemoveField(
            model_name="inboundcombodomainaddress",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="inboundcombodomainhostheader",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="inboundcombodomainsni",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="historicalconnectionrule",
            name="inboundcombogroup",
        ),
        migrations.RemoveField(
            model_name="connectionrule",
            name="inboundcombogroup",
        ),
        migrations.RemoveField(
            model_name="inboundcomboipaddress",
            name="ip",
        ),
        migrations.DeleteModel(
            name="InboundCombo",
        ),
        migrations.DeleteModel(
            name="InboundComboChoiceGroup",
        ),
        migrations.DeleteModel(
            name="InboundComboDomainAddress",
        ),
        migrations.DeleteModel(
            name="InboundComboDomainHostHeader",
        ),
        migrations.DeleteModel(
            name="InboundComboDomainSni",
        ),
        migrations.DeleteModel(
            name="InboundComboGroup",
        ),
        migrations.DeleteModel(
            name="InboundComboIPAddress",
        ),
    ]
