# Generated by Django 5.1.10 on 2025-09-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0036_nodelatestsyncstat_ip_a_and_more"),
        ("proxy_manager", "0025_remove_historicalreverse_bridge_node_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="outboundconnector",
            constraint=models.UniqueConstraint(
                fields=("outbound_type", "inbound_spec"), name="unique_outboundtype_inbound_spec_outboundconnector"
            ),
        ),
    ]
