# Generated by Django 5.1.10 on 2025-09-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0026_outboundconnector_unique_outboundtype_inbound_spec_outboundconnector"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="admin_panel_influx_delays",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalconfig",
            name="admin_panel_influx_delays",
            field=models.BooleanField(default=True),
        ),
    ]
