# Generated by Django 5.1.10 on 2025-09-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0027_config_admin_panel_influx_delays_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="usage_correction_factor",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="historicalconfig",
            name="usage_correction_factor",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
