# Generated by Django 5.1.10 on 2025-09-23 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0028_config_usage_correction_factor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboundspec",
            name="touch_node",
        ),
        migrations.AddField(
            model_name="realityspec",
            name="inbound_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="proxy_manager.inboundtype",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinboundtype",
            name="haproxy_backend",
            field=models.TextField(
                blank=True,
                help_text="{{ node_obj, inbound_tag, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinboundtype",
            name="haproxy_matcher_443",
            field=models.TextField(
                blank=True,
                help_text="{{ node_obj, inbound_tag, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinboundtype",
            name="haproxy_matcher_80",
            field=models.TextField(
                blank=True,
                help_text="{{ node_obj, inbound_tag, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinboundtype",
            name="inbound_template",
            field=models.TextField(
                help_text="{{ config, node_obj, inbound_tag, consumers_part, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinboundtype",
            name="link_template",
            field=models.TextField(
                blank=True,
                help_text="{{ subscriptionperiod_obj, connection_rule, combo_stat: {'address', 'port', 'sni', 'domainhostheader', 'shortid'}, remark_prefix }}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinboundtype",
            name="nginx_path_config",
            field=models.TextField(
                blank=True,
                help_text="{{ node_obj, inbound_tag, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaloutboundtype",
            name="xray_outbound_template",
            field=models.TextField(
                help_text="{{ source_node, dest_node, tag, nodeinternaluser, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}"
            ),
        ),
        migrations.AlterField(
            model_name="inboundtype",
            name="haproxy_backend",
            field=models.TextField(
                blank=True,
                help_text="{{ node_obj, inbound_tag, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inboundtype",
            name="haproxy_matcher_443",
            field=models.TextField(
                blank=True,
                help_text="{{ node_obj, inbound_tag, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inboundtype",
            name="haproxy_matcher_80",
            field=models.TextField(
                blank=True,
                help_text="{{ node_obj, inbound_tag, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inboundtype",
            name="inbound_template",
            field=models.TextField(
                help_text="{{ config, node_obj, inbound_tag, consumers_part, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}"
            ),
        ),
        migrations.AlterField(
            model_name="inboundtype",
            name="link_template",
            field=models.TextField(
                blank=True,
                help_text="{{ subscriptionperiod_obj, connection_rule, combo_stat: {'address', 'port', 'sni', 'domainhostheader', 'shortid'}, remark_prefix }}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inboundtype",
            name="nginx_path_config",
            field=models.TextField(
                blank=True,
                help_text="{{ node_obj, inbound_tag, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="outboundtype",
            name="xray_outbound_template",
            field=models.TextField(
                help_text="{{ source_node, dest_node, tag, nodeinternaluser, combo_stat: {'address', 'port', 'sni', 'domainhostheader'} }}"
            ),
        ),
    ]
