# Generated by Django 5.1.10 on 2025-09-26 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0029_remove_inboundspec_touch_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="sublink_debug",
            field=models.BooleanField(default=False, help_text="should be off, will reveal systems fingerprint"),
        ),
        migrations.AddField(
            model_name="connectionruleinboundspec",
            name="connector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="proxy_manager.outboundconnector",
            ),
        ),
        migrations.AddField(
            model_name="historicalconfig",
            name="sublink_debug",
            field=models.BooleanField(default=False, help_text="should be off, will reveal systems fingerprint"),
        ),
        migrations.AlterField(
            model_name="connectionruleinboundspec",
            name="spec",
            field=models.ForeignKey(
                blank=True,
                help_text="deprecated",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="proxy_manager.inboundspec",
            ),
        ),
    ]
