# Generated by Django 5.1.10 on 2025-09-26 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0030_config_sublink_debug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundspec",
            name="reality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="proxy_manager.realityspec",
            ),
        ),
    ]
