# Generated by Django 5.1.10 on 2025-10-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0031_inboundspec_reality"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="short_display",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
