# Generated by Django 5.1.10 on 2025-10-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0032_region_short_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinboundtype",
            name="type",
            field=models.CharField(default="qqq", max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inboundtype",
            name="type",
            field=models.CharField(default="qqq", max_length=63),
            preserve_default=False,
        ),
    ]
