# Generated by Django 5.1.10 on 2025-10-17 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0032_region_short_display"),
        ("telegram_bot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="defualt_timezone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="telegrambot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="telegram_bot.telegrambot",
            ),
        ),
        migrations.AddField(
            model_name="agencyplanspec",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="agencyplanspec",
            name="price_provider_args",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agencyplanspec",
            name="price_provider_key",
            field=models.SlugField(blank=True, max_length=127, null=True),
        ),
        migrations.CreateModel(
            name="AgencyUserGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=127)),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="proxy_manager.agency",
                    ),
                ),
                ("users", models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgencyUserGroupPlanSpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price_provider_key", models.SlugField(blank=True, max_length=127, null=True)),
                ("price_provider_args", models.JSONField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "agencyusergroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="proxy_manager.agencyusergroup",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="proxy_manager.subscriptionplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgencyUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="proxy_manager.agency"
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "agency"), name="unique_user_agency_agencyuser")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="agencyusergroup",
            constraint=models.UniqueConstraint(fields=("name", "agency"), name="unique_name_agency__agencyusergroup"),
        ),
        migrations.AddConstraint(
            model_name="agencyusergroupplanspec",
            constraint=models.UniqueConstraint(
                fields=("agencyusergroup", "plan"), name="unique_agencyusergroup_plan_agencyusergroupplanspec"
            ),
        ),
    ]
