# Generated by Django 5.1.10 on 2025-10-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0033_agency_defualt_timezone_agency_telegrambot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agency",
            name="telegrambot",
        ),
    ]
