# Generated by Django 5.2.8 on 2025-12-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0033_agency_default_calendar_type_agency_default_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionperiod",
            name="invoice",
        ),
        migrations.AddField(
            model_name="subscriptionprofile",
            name="send_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
