# Generated by Django 5.2.8 on 2025-12-09 19:50

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_paymentprovider_currencies"),
        ("proxy_manager", "0034_remove_subscriptionperiod_invoice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCreditUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="invoicecreditusage",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="invoicecreditusage",
            name="invoice",
        ),
        migrations.AlterModelOptions(
            name="membercredit",
            options={},
        ),
        migrations.AddField(
            model_name="agency",
            name="default_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("IRR", "Iranian Rial"), ("USD", "US Dollar")],
                default=None,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionperiod",
            name="limited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="membercredit",
            name="credit",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, default_currency="USD", max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="membercredit",
            name="credit_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("IRR", "Iranian Rial"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membercredit",
            name="debt",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, default_currency="USD", max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="membercredit",
            name="debt_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("IRR", "Iranian Rial"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="membercredit",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("credit__isnull", False), ("debt__isnull", False), _connector="OR")),
                name="membercredit_credit_or_debt",
            ),
        ),
        migrations.AddField(
            model_name="paymentcreditusage",
            name="credit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="proxy_manager.membercredit"
            ),
        ),
        migrations.AddField(
            model_name="paymentcreditusage",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="finance.payment"
            ),
        ),
        migrations.DeleteModel(
            name="InvoiceCreditUsage",
        ),
    ]
