# Generated by Django 5.2.8 on 2025-12-08 10:54

import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0034_remove_subscriptionperiod_invoice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membercredit",
            options={},
        ),
        migrations.AddField(
            model_name="subscriptionperiod",
            name="limited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="membercredit",
            name="credit",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, default_currency="USD", max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="membercredit",
            name="credit_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("IRR", "Iranian Rial"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membercredit",
            name="debt",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, default_currency="USD", max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="membercredit",
            name="debt_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("IRR", "Iranian Rial"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="membercredit",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("credit__isnull", False), ("debt__isnull", False), _connector="OR")),
                name="membercredit_credit_or_debt",
            ),
        ),
    ]
