# Generated by Django 5.1.10 on 2025-10-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0034_remove_agency_telegrambot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agency",
            old_name="defualt_timezone",
            new_name="default_timezone",
        ),
    ]
