# Generated by Django 5.2.8 on 2026-02-02 13:29

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0035_paymentcreditusage_remove_invoicecreditusage_credit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="reality_settings",
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalconfig",
            name="reality_settings",
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
