# Generated by Django 5.1.10 on 2025-10-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0035_rename_defualt_timezone_agency_default_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="default_language",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
