# Generated by Django 5.2.8 on 2025-12-09 12:41

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0035_alter_membercredit_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="default_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("IRR", "Iranian Rial"), ("USD", "US Dollar")],
                default=None,
                max_length=3,
                null=True,
            ),
        ),
    ]
