# Generated by Django 5.1.10 on 2025-10-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0036_agency_default_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="default_calendar_type",
            field=models.CharField(
                blank=True, choices=[("gregorian", "gregorian"), ("jalali", "jalali")], max_length=15, null=True
            ),
        ),
    ]
