# Generated by Django 5.2.8 on 2026-02-14 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0038_config_historicalconfig"),
        ("proxy_manager", "0036_config_reality_settings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="config",
            name="tunnel_dest_ports",
        ),
        migrations.RemoveField(
            model_name="historicalconfig",
            name="tunnel_dest_ports",
        ),
        migrations.RemoveField(
            model_name="localtunnelport",
            name="source_node",
        ),
        migrations.AddField(
            model_name="localtunnelport",
            name="dest_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="node_manager.node",
            ),
        ),
        migrations.AlterField(
            model_name="localtunnelport",
            name="tunnel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tunnel_localtunnelports",
                to="proxy_manager.connectiontunnel",
            ),
        ),
    ]
