# Generated by Django 5.2.8 on 2025-12-09 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_paymentprovider_currencies"),
        ("proxy_manager", "0036_agency_default_currency"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InvoiceCreditUsage",
            new_name="PaymentCreditUsage",
        ),
        migrations.RemoveField(
            model_name="paymentcreditusage",
            name="invoice",
        ),
        migrations.AddField(
            model_name="paymentcreditusage",
            name="payment",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="finance.payment"
            ),
            preserve_default=False,
        ),
    ]
