# Generated by Django 5.2.8 on 2026-02-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0038_config_historicalconfig"),
        ("proxy_manager", "0037_remove_config_tunnel_dest_ports_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionrule",
            name="client_json_template",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="node_manager.snippet"
            ),
        ),
        migrations.AddField(
            model_name="historicalconnectionrule",
            name="client_json_template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="node_manager.snippet",
            ),
        ),
    ]
