# Generated by Django 5.1.10 on 2025-10-25 07:19

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "__first__"),
        ("proxy_manager", "0037_agency_default_calendar_type"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agencyusergroupplanspec",
            name="agencyusergroup",
        ),
        migrations.RemoveField(
            model_name="agencyusergroupplanspec",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="agencyuser",
            name="referred_by",
        ),
        migrations.AddField(
            model_name="subscriptionperiod",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="agencyusergroups",
            field=models.ManyToManyField(related_name="+", to="proxy_manager.agencyusergroup"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="AgencyPaymentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agencyusergroup", models.ManyToManyField(related_name="+", to="proxy_manager.agencyusergroup")),
                ("payments", models.ManyToManyField(related_name="+", to="finance.paymentprovider")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgencyPlanRestriction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("capacity", models.PositiveIntegerField()),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="proxy_manager.agency"
                    ),
                ),
                (
                    "connection_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="proxy_manager.connectionrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_referral",
                        to="proxy_manager.agencyuser",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrer_referrals",
                        to="proxy_manager.agencyuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlanInvoiceItem",
            fields=[
                (
                    "invoiceitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="finance.invoiceitem",
                    ),
                ),
                ("plan_args", models.JSONField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="proxy_manager.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=("finance.invoiceitem",),
        ),
        migrations.DeleteModel(
            name="AgencyPlanSpec",
        ),
        migrations.DeleteModel(
            name="AgencyUserGroupPlanSpec",
        ),
    ]
