# Generated by Django 5.2.8 on 2025-11-11 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0038_remove_agencyusergroupplanspec_agencyusergroup_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="agencyusergroups",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="agency",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="proxy_manager.agency"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="allowed_agencyusergroups",
            field=models.ManyToManyField(blank=True, related_name="+", to="proxy_manager.agencyusergroup"),
        ),
    ]
