# Generated by Django 5.2.8 on 2025-11-13 13:59

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0039_remove_subscriptionplan_agencyusergroups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="base_currency",
            field=djmoney.models.fields.CurrencyField(
                default=None, help_text="currency unit that other prices are based on", max_length=3, null=True
            ),
        ),
    ]
