# Generated by Django 5.2.8 on 2025-11-13 14:11

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0040_subscriptionplan_base_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="base_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("IRR", "Iranian Rial"), ("USD", "US Dollar")],
                default=None,
                help_text="currency unit that other prices are based on",
                max_length=3,
                null=True,
            ),
        ),
    ]
