# Generated by Django 5.2.8 on 2025-11-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0041_alter_subscriptionplan_base_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
