# Generated by Django 5.2.8 on 2025-11-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0042_subscriptionplan_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(max_length=127),
        ),
    ]
