# Generated by Django 5.2.8 on 2025-11-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0043_alter_subscriptionplan_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubscriptionPlanInvoiceItem"
        ),
    ]
