# Generated by Django 5.2.8 on 2025-11-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0045_memberwalletinvoiceitem_membercredit_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="agencypaymenttype",
        ),
    ]
