# Generated by Django 5.2.8 on 2025-11-16 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_invoiceitem_created_by_paymentprovider_is_active"),
        ("proxy_manager", "0046_rename_agencyusergroup_agencypaymenttype_agencyusergroups"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyPaymentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agencyusergroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="proxy_manager.agencyusergroup",
                    ),
                ),
                ("payments", models.ManyToManyField(related_name="+", to="finance.paymentprovider")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
