# Generated by Django 5.2.8 on 2025-11-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy_manager", "0047_agencypaymenttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplaninvoiceitem",
            name="delivered_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="proxy_manager.subscriptionperiod",
            ),
        ),
    ]
