# Generated by Django 5.2.8 on 2025-11-21 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_invoice_completed_at_invoice_completed_by_and_more"),
        ("proxy_manager", "0048_subscriptionplaninvoiceitem_delivered_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membercredit",
            name="payed_invoice_item",
        ),
        migrations.AddField(
            model_name="memberwalletinvoiceitem",
            name="delivered_credit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="proxy_manager.membercredit",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceCreditUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="proxy_manager.membercredit"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="finance.invoice"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPeriodCreditUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="proxy_manager.membercredit"
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="proxy_manager.subscriptionperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
