# Generated by Django 4.2.17 on 2024-12-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_tid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
