# Generated by Django 5.1.7 on 2025-05-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_telegram_chat_tid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
    ]
