# Generated by Django 5.1.10 on 2025-06-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_ordering_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_timezone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
