#!/bin/bash

set -o errexit
set -o nounset


exec celery \
#    -A config.celery_app \      # i do not know why it does not work
    -b "${CELERY_BROKER_URL}" \
    flower \
    --port=5555 --address='0.0.0.0' --url_prefix=flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
