#!/bin/bash

set -o errexit
set -o nounset

#    -A config.celery_app \      # i do not know why it does not work
exec celery \
    -b "${CELERY_BROKER_URL}" \
    flower \
    --port=5555 --address='0.0.0.0' --url_prefix=flower
