# Generated by Django 5.2.8 on 2026-02-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="block_detected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
