# Generated by Django 5.1.10 on 2025-10-17 15:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegramuser",
            old_name="tbot",
            new_name="bot",
        ),
        migrations.RenameField(
            model_name="telegramuser",
            old_name="user_tid",
            new_name="tid",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="last_accessed_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 17, 15, 28, 53, 852190, tzinfo=datetime.timezone.utc)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="tadded_to_attachment_menu",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="tfirst_name",
            field=models.CharField(default="adad", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="tis_premium",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="tlanguage_code",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="tlast_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="tusername",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegramuserprofiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
