# Generated by Django 5.1.10 on 2025-10-18 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0002_rename_tbot_telegramuser_bot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="telegramuser",
            name="unique_tuser_tbot",
        ),
        migrations.AddConstraint(
            model_name="telegramuser",
            constraint=models.UniqueConstraint(fields=("tid", "bot"), name="unique_tuser_tbot"),
        ),
    ]
