# Generated by Django 4.2.16 on 2024-10-27 15:26

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='easytiernode',
            name='ipv4',
            field=netfields.fields.InetAddressField(blank=True, help_text='this is a stational entity', max_length=39, null=True),
        ),
    ]
