# Generated by Django 4.2.16 on 2024-11-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0002_customconfigtemplate_custom_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programbinary',
            name='file',
            field=models.FileField(upload_to='protected/'),
        ),
        migrations.AlterField(
            model_name='programbinary',
            name='hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
