# Generated by Django 4.2.16 on 2024-11-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0002_customconfigtemplate_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customconfigtemplate',
            name='config_file_ext',
            field=models.CharField(blank=True, null=True),
        ),
    ]
