# Generated by Django 4.2.16 on 2024-11-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0003_alter_programbinary_file_alter_programbinary_hash'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nodepublicip',
            constraint=models.UniqueConstraint(fields=('ip', 'node'), name='unique_node_ip'),
        ),
    ]
