# Generated by Django 4.2.16 on 2024-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0003_customconfigtemplate_config_file_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='easytiernode',
            name='mtu',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
