# Generated by Django 4.2.16 on 2024-11-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0004_easytiernode_mtu'),
    ]

    operations = [
        migrations.AddField(
            model_name='easytiernode',
            name='rpc_portal_port',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='easytiernode',
            name='mtu',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
