# Generated by Django 4.2.16 on 2024-11-06 19:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('node_manager', '0004_nodepublicip_unique_node_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipv4', netfields.fields.InetAddressField(blank=True, help_text='the internal ip that is constantly changed, this is a stational entity', max_length=39, null=True, validators=[django.core.validators.validate_ipv4_address])),
                ('ipv6', netfields.fields.InetAddressField(blank=True, help_text='the internal ip that is constantly changed, this is a stational entity', max_length=39, null=True, validators=[django.core.validators.validate_ipv6_address])),
                ('ip_a_container_ipv4_extractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipacontaineripv4extractor_containerspecs', to='utils.textextractor')),
                ('ip_a_container_ipv6_extractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipacontaineripv6extractor_containerspecs', to='utils.textextractor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='node',
            name='container_spec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='containerspec_nodes', to='node_manager.containerspec'),
        ),
    ]
