# Generated by Django 4.2.16 on 2024-11-17 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0005_easytiernode_rpc_portal_port_alter_easytiernode_mtu'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeLatestSyncStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_at', models.DateTimeField()),
                ('respond_at', models.DateTimeField(null=True)),
                ('request_headers', models.JSONField()),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField(null=True)),
                ('count_up_to_now', models.BigIntegerField()),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_nodesyncstat', to='node_manager.node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
