# Generated by Django 4.2.16 on 2024-11-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0006_nodelatestsyncstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='easytiernode',
            name='latency_first',
            field=models.BooleanField(default=False),
        ),
    ]
