# Generated by Django 4.2.17 on 2024-12-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0007_easytiernode_latency_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodelatestsyncstat',
            name='agent_spec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
