# Generated by Django 4.2.17 on 2024-12-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0008_nodelatestsyncstat_agent_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
