# Generated by Django 4.2.17 on 2024-12-29 09:02

from django.db import migrations, models
import django.db.models.deletion


def populate(apps, schema_editor):
    CustomConfig = apps.get_model('node_manager', 'CustomConfig')
    CustomConfigDependantFile = apps.get_model('node_manager', 'CustomConfigDependantFile')
    for i in CustomConfig.objects.all():
        CustomConfigDependantFile.objects.create(
            customconfig=i,
            key="first",
            template=i.template,
            template_extension=i.config_file_ext
        )

def reverse_populate(apps, schema_editor):
    CustomConfig = apps.get_model('node_manager', 'CustomConfig')
    CustomConfigDependantFile = apps.get_model('node_manager', 'CustomConfigDependantFile')
    for i in CustomConfig.objects.all():
        customconfigdependantfile_qs = CustomConfigDependantFile.objects.filter(customconfig=i)
        if customconfigdependantfile_qs.count() != 1:
            continue
        customconfigdependantfile_obj = customconfigdependantfile_qs.first()
        i.template = customconfigdependantfile_obj.template
        i.config_file_ext = customconfigdependantfile_obj.template_extension
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('node_manager', '0009_alter_node_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomConfigTemplate",
            new_name="CustomConfig"
        ),
        migrations.RenameModel(
            old_name="NodeCustomConfigTemplate",
            new_name="NodeCustomConfig"
        ),
        migrations.RemoveConstraint(
            model_name='nodecustomconfig',
            name='unique_node_config_template',
        ),
        migrations.RenameField(
            model_name="NodeCustomConfig",
            old_name="config_template",
            new_name="custom_config",
        ),
        migrations.AddConstraint(
            model_name='nodecustomconfig',
            constraint=models.UniqueConstraint(fields=('node', 'custom_config'), name='unique_node_custom_config'),
        ),
        migrations.CreateModel(
            name='CustomConfigDependantFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField()),
                ('template', models.TextField(help_text='{node_obj}')),
                ('template_extension', models.CharField(blank=True, null=True)),
                ('customconfig',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependantfiles',
                                   to='node_manager.customconfig')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customconfigdependantfile',
            constraint=models.UniqueConstraint(fields=('customconfig', 'key'), name='unique_slug_customconfig'),
        ),
        migrations.RunPython(code=populate, reverse_code=reverse_populate),
        migrations.RemoveField(
            model_name='customconfig',
            name='config_file_ext',
        ),
        migrations.RemoveField(
            model_name='customconfig',
            name='template',
        ),
        migrations.AlterField(
            model_name='customconfig',
            name='program_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='programversion_customconfigs', to='node_manager.programversion'),
        ),
        migrations.AlterField(
            model_name='nodecustomconfig',
            name='custom_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodecustomconfigs',
                                    to='node_manager.customconfig'),
        ),
        migrations.AlterField(
            model_name='nodecustomconfig',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_customconfigs',
                                    to='node_manager.node'),
        ),
    ]
