# Generated by Django 4.2.17 on 2025-01-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0011_node_default_cert'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSupervisorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xml_rpc_api_expose_port', models.IntegerField(blank=True, null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisorconfig', to='node_manager.node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
