# Generated by Django 4.2.17 on 2025-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0012_nodesupervisorconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customconfigdependantfile',
            name='template_extension',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
