# Generated by Django 4.2.17 on 2025-01-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0013_alter_customconfigdependantfile_template_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('program_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programversion_xrayconfig', to='node_manager.programversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
