# Generated by Django 4.2.17 on 2025-01-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0013_alter_customconfigdependantfile_template_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='easytiernode',
            name='stderr_action_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'nothing'), (1, 'to loki')], default=0),
        ),
        migrations.AddField(
            model_name='easytiernode',
            name='stdout_action_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'nothing'), (1, 'to loki')], default=0),
        ),
        migrations.AddField(
            model_name='nodecustomconfig',
            name='stderr_action_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'nothing'), (1, 'to loki')], default=0),
        ),
        migrations.AddField(
            model_name='nodecustomconfig',
            name='stdout_action_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'nothing'), (1, 'to loki')], default=0),
        ),
    ]
