# Generated by Django 4.2.17 on 2025-02-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0014_easytiernode_stderr_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='collect_metrics',
            field=models.BooleanField(default=False),
        ),
    ]
