# Generated by Django 4.2.17 on 2025-02-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0015_node_collect_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodelatestsyncstat',
            name='request_payload',
        ),
    ]
