# Generated by Django 4.2.17 on 2025-02-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0016_remove_nodelatestsyncstat_request_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='collect_logs',
            field=models.BooleanField(default=False),
        ),
    ]
