# Generated by Django 4.2.17 on 2025-02-11 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0017_node_collect_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='easytiernode',
            name='preferred_program_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferredprogramversion_easytiernode', to='node_manager.programversion'),
        ),
    ]
