# Generated by Django 5.1.7 on 2025-04-28 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0018_easytiernode_preferred_program_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnsibleTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("celery_task_id", models.UUIDField(blank=True, null=True)),
                ("playbook_content", models.TextField()),
                ("status", models.PositiveSmallIntegerField(choices=[(1, "started"), (2, "finished")])),
                ("logs", models.TextField(blank=True)),
                ("result", models.JSONField(null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnsibleTaskNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ok", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("dark", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("changed", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("failures", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("result", models.JSONField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="O2Spec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_domain", models.URLField(max_length=255)),
                ("api_key", models.CharField(max_length=255)),
                ("interval_sec", models.PositiveSmallIntegerField()),
                ("working_dir", models.CharField(max_length=255)),
                ("sentry_dsn", models.URLField(blank=True, max_length=255, null=True)),
                ("full_control_supervisord", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Snippet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.SlugField()),
                ("template", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="customconfigdependantfile",
            old_name="template_extension",
            new_name="name_extension",
        ),
        migrations.AddField(
            model_name="customconfigdependantfile",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customconfigdependants",
                to="node_manager.programversion",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="ssh_pass",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="ssh_port",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="ssh_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="tmp_xray",
            field=models.BooleanField(default=False),
        ),
    ]
