# Generated by Django 5.1.7 on 2025-04-28 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0019_big_migration_1_1"),
        ("proxy_manager", "0001_big_migration_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicip",
            name="isp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="isp_publicips",
                to="proxy_manager.isp",
            ),
        ),
        migrations.AddField(
            model_name="publicip",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="region_publicips",
                to="proxy_manager.region",
            ),
        ),
        migrations.AlterField(
            model_name="customconfig",
            name="program_version",
            field=models.ForeignKey(
                blank=True,
                help_text="depracated",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programversion_customconfigs",
                to="node_manager.programversion",
            ),
        ),
        migrations.AlterField(
            model_name="customconfig",
            name="run_opts_template",
            field=models.TextField(help_text="{node_obj}, *#path:key#*"),
        ),
        migrations.AlterField(
            model_name="customconfigdependantfile",
            name="template",
            field=models.TextField(blank=True, help_text="{node_obj}", null=True),
        ),
        migrations.AddField(
            model_name="ansibletasknode",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="node_ansibletasks", to="node_manager.node"
            ),
        ),
        migrations.AddField(
            model_name="ansibletasknode",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="task_nodes", to="node_manager.ansibletask"
            ),
        ),
        migrations.AddField(
            model_name="o2spec",
            name="node",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="o2spec", to="node_manager.node"
            ),
        ),
        migrations.AddField(
            model_name="o2spec",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="program_o2spec",
                to="node_manager.programversion",
            ),
        ),
        migrations.AddField(
            model_name="o2spec",
            name="ansible_deploy_snippet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ansibledeploysnippet_o2specs",
                to="node_manager.snippet",
            ),
        ),
        migrations.AddField(
            model_name="ansibletask",
            name="playbook_snippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playbooksnippet_ansibletasks",
                to="node_manager.snippet",
            ),
        ),
    ]
