# Generated by Django 4.2.17 on 2025-03-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0010_isp_region_connectionrule_and_more'),
        ('node_manager', '0019_xrayconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicip',
            name='isp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='isp_publicips', to='proxy_manager.isp'),
        ),
    ]
