# Generated by Django 4.2.17 on 2025-03-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0012_alter_connectionrule_xray_rules_template'),
        ('node_manager', '0020_publicip_isp'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicip',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_publicips', to='proxy_manager.region'),
        ),
    ]
