# Generated by Django 5.1.7 on 2025-05-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0020_big_migration_1_2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ansibletask",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="ansibletasknode",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="containerspec",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="customconfig",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="customconfigdependantfile",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="easytiernetwork",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="easytiernode",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="easytiernodelistener",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="easytiernodepeer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="gostclientnode",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="node",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="nodeapikey",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="nodecustomconfig",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="nodeinnerprogram",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="nodelatestsyncstat",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="nodepublicip",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="nodesupervisorconfig",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="o2spec",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="program",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="programbinary",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="programversion",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="publicip",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="snippet",
            options={"ordering": ["-created_at"]},
        ),
    ]
