# Generated by Django 5.1.7 on 2025-05-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0021_ordering_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupervisorProcessInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("start", models.DateTimeField()),
                ("stop", models.DateTimeField(blank=True, null=True)),
                ("captured_at", models.DateTimeField()),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "stopped"),
                            (10, "starting"),
                            (20, "running"),
                            (30, "backoff"),
                            (40, "stopping"),
                            (100, "exited"),
                            (200, "fatal"),
                            (1000, "unknown"),
                        ]
                    ),
                ),
                ("statename", models.CharField(max_length=255)),
                ("spawnerr", models.CharField(blank=True, max_length=255, null=True)),
                ("exitstatus", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("stdout_logfile", models.CharField(max_length=255)),
                ("stderr_logfile", models.CharField(max_length=255)),
                ("pid", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_processstates",
                        to="node_manager.node",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
    ]
