# Generated by Django 5.1.7 on 2025-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0021_publicip_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="tmp_xray",
            field=models.BooleanField(default=False),
        ),
    ]
