# Generated by Django 5.1.7 on 2025-04-22 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0022_node_tmp_xray"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customconfigdependantfile",
            old_name="template_extension",
            new_name="name_extension",
        ),
        migrations.AddField(
            model_name="customconfigdependantfile",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customconfigdependants",
                to="node_manager.programversion",
            ),
        ),
        migrations.AlterField(
            model_name="customconfig",
            name="run_opts_template",
            field=models.TextField(help_text="{node_obj}, *#path:key#*"),
        ),
        migrations.AlterField(
            model_name="customconfigdependantfile",
            name="template",
            field=models.TextField(blank=True, help_text="{node_obj}", null=True),
        ),
    ]
