# Generated by Django 5.1.7 on 2025-04-24 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0023_rename_template_extension_customconfigdependantfile_name_extension_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customconfig",
            name="program_version",
            field=models.ForeignKey(
                blank=True,
                help_text="depracated",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programversion_customconfigs",
                to="node_manager.programversion",
            ),
        ),
        migrations.DeleteModel(
            name="XrayConfig",
        ),
    ]
