# Generated by Django 5.1.7 on 2025-06-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_siteconfiguration_sync_brake"),
        ("node_manager", "0023_alter_supervisorprocessinfo_pid"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicip",
            name="asn",
            field=models.PositiveIntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="publicip",
            name="same_asn_domain",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="core.domain"
            ),
        ),
    ]
