# Generated by Django 5.1.10 on 2025-07-04 17:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0025_historicalcustomconfig_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SupervisorProcessInfo",
        ),
        migrations.CreateModel(
            name="SupervisorProcessInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "perv_state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "stopped"),
                            (10, "starting"),
                            (20, "running"),
                            (30, "backoff"),
                            (40, "stopping"),
                            (100, "exited"),
                            (200, "fatal"),
                            (1000, "unknown"),
                        ]
                    ),
                ),
                (
                    "last_state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "stopped"),
                            (10, "starting"),
                            (20, "running"),
                            (30, "backoff"),
                            (40, "stopping"),
                            (100, "exited"),
                            (200, "fatal"),
                            (1000, "unknown"),
                        ]
                    ),
                ),
                ("perv_statename", models.CharField(max_length=255)),
                ("last_statename", models.CharField(max_length=255)),
                ("perv_start", models.DateTimeField()),
                ("last_start", models.DateTimeField()),
                ("perv_stop", models.DateTimeField(blank=True, null=True)),
                ("last_stop", models.DateTimeField(blank=True, null=True)),
                ("perv_spawnerr", models.CharField(blank=True, max_length=255, null=True)),
                ("last_spawnerr", models.CharField(blank=True, max_length=255, null=True)),
                ("perv_exitstatus", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("last_exitstatus", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("perv_pid", models.PositiveBigIntegerField(blank=True, null=True)),
                ("last_pid", models.PositiveBigIntegerField(blank=True, null=True)),
                ("stdout_logfile", models.CharField(max_length=255)),
                ("stderr_logfile", models.CharField(max_length=255)),
                ("perv_captured_at", models.DateTimeField()),
                ("last_captured_at", models.DateTimeField()),
                ("perv_changed_at", models.DateTimeField()),
                ("last_changed_at", models.DateTimeField()),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_processstates",
                        to="node_manager.node",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_captured_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("node", "name"), name="unique_name_node_for_supervisor")
                ],
            },
        ),
    ]
