# Generated by Django 5.1.7 on 2025-04-25 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0025_ansibletask_snippet_node_ssh_pass_node_ssh_port_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="ansible_deploy_snippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ansibledeploysnippet_nodes",
                to="node_manager.snippet",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="o2_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="o2program_nodes",
                to="node_manager.programversion",
            ),
        ),
    ]
