# Generated by Django 5.1.10 on 2025-07-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0026_recreate_supervisorprocessinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodelatestsyncstat",
            name="config",
            field=models.JSONField(null=True),
        ),
    ]
