# Generated by Django 5.1.10 on 2025-07-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0027_nodelatestsyncstat_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supervisorprocessinfo",
            name="last_exitstatus",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supervisorprocessinfo",
            name="perv_exitstatus",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
