# Generated by Django 5.1.7 on 2025-04-25 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0027_ansibletask_result_ansibletask_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="ansible_deploy_snippet",
        ),
        migrations.RemoveField(
            model_name="node",
            name="o2_program",
        ),
        migrations.CreateModel(
            name="O2Spec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_domain", models.URLField(max_length=255)),
                ("api_key", models.CharField(max_length=255)),
                ("interval_sec", models.PositiveSmallIntegerField()),
                ("working_dir", models.CharField(max_length=255)),
                ("sentry_dsn", models.URLField(blank=True, max_length=255, null=True)),
                ("full_control_supervisord", models.BooleanField(default=False)),
                (
                    "ansible_deploy_snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ansibledeploysnippet_o2specs",
                        to="node_manager.snippet",
                    ),
                ),
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="o2spec", to="node_manager.node"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_o2spec",
                        to="node_manager.programversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
