# Generated by Django 5.1.10 on 2025-07-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0028_alter_supervisorprocessinfo_last_exitstatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ansibletask",
            name="extravars",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ansibletask",
            name="inventory_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
