# Generated by Django 5.1.7 on 2025-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0028_remove_node_ansible_deploy_snippet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ansibletask",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ansibletask",
            name="logs",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ansibletask",
            name="name",
            field=models.CharField(default="fdfdfd", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ansibletasknode",
            name="result",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="ansibletasknode",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "dark"), (3, "changed"), (4, "failure"), (5, "ok")], null=True
            ),
        ),
    ]
