# Generated by Django 5.1.7 on 2025-04-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0029_ansibletask_finished_at_ansibletask_logs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ansibletasknode",
            name="status",
        ),
        migrations.AddField(
            model_name="ansibletasknode",
            name="changed",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ansibletasknode",
            name="dark",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ansibletasknode",
            name="failures",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ansibletasknode",
            name="ok",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
