# Generated by Django 5.1.10 on 2025-07-15 07:13

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Exists, F


def populate(apps, schema_editor):
    Node = apps.get_model('node_manager', 'Node')
    O2Spec = apps.get_model('node_manager', 'O2Spec')
    sub_qs = O2Spec.objects.filter(node_id=OuterRef("id"))
    Node.objects.filter(Exists(sub_qs))\
        .update(ansible_deploy_snippet_id=sub_qs.values("ansible_deploy_snippet_id"))

def reverse_populate(apps, schema_editor):
    Node = apps.get_model('node_manager', 'Node')
    O2Spec = apps.get_model('node_manager', 'O2Spec')
    sub_qs = Node.objects.filter(id=OuterRef("node_id"))
    O2Spec.objects.filter(node__ansible_deploy_snippet__isnull=False)\
        .update(ansible_deploy_snippet_id=sub_qs.values("ansible_deploy_snippet_id"))


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0029_ansibletask_extravars_ansibletask_inventory_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="ansible_deploy_snippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ansibledeploysnippet_o2specs",
                to="node_manager.snippet",
            ),
        ),
        migrations.AlterField(
            model_name="o2spec",
            name="ansible_deploy_snippet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ansibledeploysnippet_o2specs",
                to="node_manager.snippet",
                null=True,  # for reverse
            ),
        ),
        migrations.RunPython(populate, reverse_code=reverse_populate),
        migrations.RemoveField(
            model_name="o2spec",
            name="ansible_deploy_snippet",
        ),
    ]
