# Generated by Django 5.1.7 on 2025-04-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0030_remove_ansibletasknode_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ansibletask",
            name="celery_task_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
