# Generated by Django 5.1.10 on 2025-07-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_publickey"),
        ("node_manager", "0030_remove_o2spec_ansible_deploy_snippet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="ssh_public_keys",
            field=models.ManyToManyField(blank=True, related_name="+", to="core.publickey"),
        ),
    ]
