# Generated by Django 5.1.10 on 2025-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0031_node_ssh_public_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="o2spec",
            name="keep_latest_config",
            field=models.BooleanField(default=True),
        ),
    ]
