# Generated by Django 5.1.10 on 2025-07-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0032_o2spec_keep_latest_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="is_revoked",
            field=models.BooleanField(default=False),
        ),
    ]
