# Generated by Django 5.1.10 on 2025-08-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0033_node_is_revoked"),
        ("proxy_manager", "0021_realityspec"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicip",
            name="same_asn_domain",
        ),
    ]
