# Generated by Django 5.1.10 on 2025-08-18 20:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0034_remove_publicip_same_asn_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="downtime_attended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nodelatestsyncstat",
            name="expected_interval_coefficient",
            field=models.DecimalField(decimal_places=2, default=Decimal("1.5"), max_digits=6),
        ),
        migrations.AddField(
            model_name="nodelatestsyncstat",
            name="mean_interval_up_to_now",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nodelatestsyncstat",
            name="config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nodelatestsyncstat",
            name="initiated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nodelatestsyncstat",
            name="request_headers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nodelatestsyncstat",
            name="respond_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nodelatestsyncstat",
            name="response_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
