# Generated by Django 5.1.10 on 2025-08-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0035_node_downtime_attended_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodelatestsyncstat",
            name="ip_a",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nodepublicip",
            name="last_status_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nodepublicip",
            name="status",
            field=models.PositiveSmallIntegerField(choices=[(1, "unknown"), (2, "ok"), (3, "problem")], default=1),
        ),
        migrations.CreateModel(
            name="NetplanConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.SlugField(unique=True)),
                ("dnsv4", models.CharField(max_length=255)),
                ("dnsv6", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="node_manager.snippet"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="node",
            name="netplan_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="node_manager.netplanconfiguration",
            ),
        ),
    ]
