# Generated by Django 5.2.8 on 2025-11-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0036_nodelatestsyncstat_ip_a_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisorprocessinfo",
            name="is_down_attended",
            field=models.BooleanField(default=False),
        ),
    ]
