# Generated by Django 5.2.8 on 2026-02-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0037_supervisorprocessinfo_is_down_attended"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("admin_show_node_metrics", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
