# Generated by Django 5.2.8 on 2026-02-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_manager", "0038_config_historicalconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodepublicip",
            name="is_nat",
            field=models.BooleanField(default=False),
        ),
    ]
