# Generated by Django 5.1.7 on 2025-05-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textextractor",
            options={"ordering": ["-created_at"]},
        ),
    ]
