# Generated by Django 4.2.17 on 2024-12-19 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptographicObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('algorithm', models.PositiveSmallIntegerField(verbose_name=[(1, 'RSA'), (2, 'ECDSA')])),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('content', models.TextField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('cryptographicobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.cryptographicobject')),
                ('passphrase', models.CharField(max_length=255, null=True)),
                ('key_length', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.cryptographicobject',),
        ),
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('cryptographicobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.cryptographicobject')),
                ('parent_public_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.publickey')),
                ('private_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.privatekey')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.cryptographicobject',),
        ),
    ]
