# Generated by Django 4.2.17 on 2025-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_basic_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='basic_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='basic_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
