# Generated by Django 4.2.17 on 2025-02-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_siteconfiguration_basic_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='loki_batch_size',
            field=models.PositiveBigIntegerField(default=1048576),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_nginx_stderr_action_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'nothing'), (1, 'to loki')], default=0),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_nginx_stdout_action_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'nothing'), (1, 'to loki')], default=0),
        ),
    ]
