# Generated by Django 4.2.17 on 2025-02-02 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0015_node_collect_metrics'),
        ('core', '0004_siteconfiguration_loki_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_telegraf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='node_manager.programversion'),
        ),
    ]
