# Generated by Django 4.2.17 on 2025-03-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0019_xrayconfig'),
        ('core', '0005_siteconfiguration_main_telegraf'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_haproxy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='node_manager.programversion'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_xray',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='node_manager.programversion'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='main_nginx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='node_manager.programversion'),
        ),
    ]
