# Generated by Django 5.1.7 on 2025-04-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_dnsprovider_domain_domaincertificate_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="domain",
            name="either_root_or_isnotroot",
        ),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("root__isnull", True), ("is_root", False), _connector="OR")),
                name="either_root_or_isnotroot",
            ),
        ),
    ]
