# Generated by Django 5.1.7 on 2025-05-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_siteconfiguration_main_goingto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certbotinfo",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="certificate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="certificatetask",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dnsprovider",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="domain",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="domaincertificate",
            options={"ordering": ["-created_at"]},
        ),
    ]
