# Generated by Django 5.1.7 on 2025-04-07 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_domain_either_root_or_isnotroot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domaincertificate",
            name="subdomain",
        ),
        migrations.AlterField(
            model_name="domain",
            name="root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subdomains",
                to="core.domain",
            ),
        ),
    ]
