# Generated by Django 5.1.7 on 2025-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_ordering_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="sync_brake",
            field=models.BooleanField(default=True),
        ),
    ]
