# Generated by Django 5.1.7 on 2025-04-10 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_domaincertificate_subdomain_alter_domain_root"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("certbot_cert_uuid", models.UUIDField()),
                ("task_type", models.PositiveSmallIntegerField(choices=[(1, "Issue"), (2, "Renewal")])),
                ("logs", models.TextField(blank=True)),
                ("is_closed", models.BooleanField()),
                ("is_success", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="domaincertificate",
            name="certificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate_domaincertificates",
                to="core.certificate",
            ),
        ),
        migrations.CreateModel(
            name="CertbotCert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, unique=True)),
                ("cert_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "certificate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_certbot",
                        to="core.certificate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
