# Generated by Django 5.1.10 on 2025-07-15 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_siteconfiguration_sync_brake"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("algorithm", models.PositiveSmallIntegerField(verbose_name=[(1, "RSA"), (2, "ECDSA")])),
                ("content", models.TextField()),
                (
                    "private_key",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.privatekey"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
